var pages = [{'name': 'public final class OraBench', 'description':'ch.konnexions.orabench.OraBench', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/index.html', 'searchKey':'OraBench'},
{'name': 'OraBench OraBench()', 'description':'ch.konnexions.orabench.OraBench.OraBench', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/-ora-bench.html', 'searchKey':'OraBench'},
{'name': 'final Properties getConfig()', 'description':'ch.konnexions.orabench.OraBench.<get-config>', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/get-config.html', 'searchKey':'<get-config>'},
{'name': 'final String getFileConfigurationName()', 'description':'ch.konnexions.orabench.OraBench.<get-fileConfigurationName>', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/get-file-configuration-name.html', 'searchKey':'<get-fileConfigurationName>'},
{'name': 'final Boolean getIsDebug()', 'description':'ch.konnexions.orabench.OraBench.<get-isDebug>', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/get-is-debug.html', 'searchKey':'<get-isDebug>'},
{'name': 'final Logger getLogger()', 'description':'ch.konnexions.orabench.OraBench.<get-logger>', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/get-logger.html', 'searchKey':'<get-logger>'},
{'name': 'final Unit runBenchmark()', 'description':'ch.konnexions.orabench.OraBench.runBenchmark', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench/run-benchmark.html', 'searchKey':'runBenchmark'},
{'name': 'public final class OraBenchKt', 'description':'ch.konnexions.orabench.OraBenchKt', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench-kt/index.html', 'searchKey':'OraBenchKt'},
{'name': 'final Unit main(Array<String> args)', 'description':'ch.konnexions.orabench.main', 'location':'ora_bench/ch.konnexions.orabench/-ora-bench-kt/main.html', 'searchKey':'main'}]
