---
dist: xenial

sudo: true

language: erlang
otp_release:
  - 20.3

env:
  matrix:
    - ORA_BENCH_BENCHMARK_DATABASE=db_12_2_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_18_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1

before_install:
  - sudo apt update
  - sudo apt install software-properties-common
  # Elixir -----------------------------------------------------------------------
  - travis_fold start "Setting up Elixir"
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  - cd ~/.asdf
  - git checkout "$(git describe --abbrev=0 --tags)"
  - echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
  - echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
  - cd /home/travis/build/KonnexionsGmbH/ora_bench
  - . ~/.bashrc
  - asdf plugin-add Elixir https://github.com/asdf-vm/asdf-elixir
  - asdf install Elixir 1.9.4   
  - asdf global Elixir 1.9.4
  - elixir -v
  - mix local.hex --force
  - mix local.rebar --force
  - rebar3 version
  - travis_fold end   "Setting up Elixir"
  # Java -------------------------------------------------------------------------
  - travis_fold start "Setting up Java"
  - sudo apt install default-jdk
  - java -version
  - travis_fold end   "Setting up Java"
  # Oracle Instant Client for Linux x86-64 (64-bit) ------------------------------
  - travis_fold start "Setting up Oracle Instant Client"
  - sudo apt-get install libaio1
  - export LD_LIBRARY_PATH=$PWD/priv/oracle/instantclient-linux.x64/instantclient_19_5:$LD_LIBRARY_PATH
  - sudo chmod +x $PWD/priv/oracle/instantclient-linux.x64/instantclient_19_5/sqlplus
  - travis_fold end   "Setting up Oracle Instant Client"
  # Python -----------------------------------------------------------------------
  - travis_fold start "Setting up Python"
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt install python3
  - python3 --version
  - sudo apt install python3-venv
  - python3 -m venv _build/ora_bench-env
  - source _build/ora_bench-env/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade cx_Oracle
  - travis_fold end   "Setting up Python"

script:
  - travis_fold start "Setting environment variables"
  - export ORA_BENCH_MULTIPLE_RUN=true

  - export ORA_BENCH_BENCHMARK_COMMENT='Standard tests (Travis CI)'
  - export ORA_BENCH_CONNECTION_HOST=0.0.0.0
  - export ORA_BENCH_CONNECTION_PORT=1521
  - export ORA_BENCH_FILE_CONFIGURATION_NAME=priv/properties/ora_bench.properties
  - export ORA_BENCH_JAVA_CLASSPATH=.:priv/java_jar/*
  - export ORA_BENCH_PASSWORD_SYS=oracle

  - export ORA_BENCH_RUN_DB_12_2_EE=true
  - export ORA_BENCH_RUN_DB_18_3_EE=true
  - export ORA_BENCH_RUN_DB_19_3_EE=true

  - export ORA_BENCH_RUN_CX_ORACLE_PYTHON=true
  - export ORA_BENCH_RUN_JAMDB_ORACLE_ELIXIR=false
  - export ORA_BENCH_RUN_JDBC_JAVA=true
  - export ORA_BENCH_RUN_ODPI_C=true
  - export ORA_BENCH_RUN_ORANIF_ERLANG=true
  - export ORA_BENCH_RUN_SERIES=true

  - export ORA_BENCH_BENCHMARK_BATCH_SIZE_DEFAULT=256
  - export ORA_BENCH_BENCHMARK_CORE_MULTIPLIER_DEFAULT=0
  - export ORA_BENCH_BENCHMARK_TRANSACTION_SIZE_DEFAULT=512
  - travis_fold end   "Setting environment variables"

  - git pull
  - ./scripts/run_bench_setup.sh
  - ./scripts/run_bench_database_series.sh
  - ./scripts/run_bench_finalise.sh

after_success:
  - ./scripts/run_bench_travis_push.sh
