---
dist: xenial

sudo: true

language: erlang
otp_release:
  - 23.0

env:
  matrix:
    - ORA_BENCH_BENCHMARK_DATABASE=db_12_2_ee ORA_BENCH_BENCHMARK_JAMDB=false
    - ORA_BENCH_BENCHMARK_DATABASE=db_12_2_ee ORA_BENCH_BENCHMARK_JAMDB=true
    - ORA_BENCH_BENCHMARK_DATABASE=db_18_3_ee ORA_BENCH_BENCHMARK_JAMDB=false
    - ORA_BENCH_BENCHMARK_DATABASE=db_18_3_ee ORA_BENCH_BENCHMARK_JAMDB=true
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_BENCHMARK_JAMDB=false
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_BENCHMARK_JAMDB=true
      
    - cx_Oracle Python ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=true  ORA_BENCH_RUN_GODROR_GO=false ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=false ORA_BENCH_RUN_JDBC_JAVA=false ORA_BENCH_RUN_ODPI_C=false ORA_BENCH_RUN_ORANIF_ELIXIR=false ORA_BENCH_RUN_ORANIF_ERLANG=false
    - GoDROR    Go     ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=false ORA_BENCH_RUN_GODROR_GO=true  ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=false ORA_BENCH_RUN_JDBC_JAVA=false ORA_BENCH_RUN_ODPI_C=false ORA_BENCH_RUN_ORANIF_ELIXIR=false ORA_BENCH_RUN_ORANIF_ERLANG=false
    - JamDB     Erlang ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=false ORA_BENCH_RUN_GODROR_GO=false ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=true  ORA_BENCH_RUN_JDBC_JAVA=false ORA_BENCH_RUN_ODPI_C=false ORA_BENCH_RUN_ORANIF_ELIXIR=false ORA_BENCH_RUN_ORANIF_ERLANG=false
    - JDBC      Java   ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=false ORA_BENCH_RUN_GODROR_GO=false ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=false ORA_BENCH_RUN_JDBC_JAVA=true  ORA_BENCH_RUN_ODPI_C=false ORA_BENCH_RUN_ORANIF_ELIXIR=false ORA_BENCH_RUN_ORANIF_ERLANG=false
    - ODPI      C      ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=false ORA_BENCH_RUN_GODROR_GO=false ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=false ORA_BENCH_RUN_JDBC_JAVA=false ORA_BENCH_RUN_ODPI_C=true  ORA_BENCH_RUN_ORANIF_ELIXIR=false ORA_BENCH_RUN_ORANIF_ERLANG=false
    - oranif    Elixir ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=false ORA_BENCH_RUN_GODROR_GO=false ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=false ORA_BENCH_RUN_JDBC_JAVA=false ORA_BENCH_RUN_ODPI_C=false ORA_BENCH_RUN_ORANIF_ELIXIR=true  ORA_BENCH_RUN_ORANIF_ERLANG=false
    - oranif    Erlang ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_RUN_CX_ORACLE_PYTHON=false ORA_BENCH_RUN_GODROR_GO=false ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=false ORA_BENCH_RUN_JDBC_JAVA=false ORA_BENCH_RUN_ODPI_C=false ORA_BENCH_RUN_ORANIF_ELIXIR=false ORA_BENCH_RUN_ORANIF_ERLANG=true

script:
  # Prepare installation process -------------------------------------------------
  - travis_fold start "Prepare_installation_process"
  - export VERSION_ELIXIR=1.10.4
  - export VERSION_GO=1.15.1
  - export VERSION_GRADLE=6.6.1
  - export VERSION_JAVA=14.0.2
  - export VERSION_ORACLE_INSTANT_CLIENT=19_8
    
  - sudo apt update -q
  - sudo apt install -q software-properties-common
  - sudo apt-get install -q lsb-core
  - travis_fold end   "Prepare_installation_process"

  # Elixir -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Elixir"
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  - cd ~/.asdf
  - git checkout "$(git describe --abbrev=0 --tags)"
  - echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
  - echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
  - cd /home/travis/build/KonnexionsGmbH/ora_bench
  - . ~/.bashrc
  - asdf plugin-add Elixir https://github.com/asdf-vm/asdf-elixir
  - asdf install Elixir ${VERSION_ELIXIR}   
  - asdf global Elixir ${VERSION_ELIXIR}
  - mix local.hex --force
  - mix local.rebar --force
  - travis_fold end   "Setting_up_Elixir"

  # Go ---------------------------------------------------------------------------
  - travis_fold start "Setting_up_Go"
  - wget -q https://dl.google.com/go/go${VERSION_GO}.linux-amd64.tar.gz
  - tar -xf go${VERSION_GO}.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOPATH=$HOME/build/KonnexionsGmbH/ora_bench/src_go/go
  - export GOROOT=/usr/local/go
  - export PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH}
  - travis_fold end   "Setting_up_Go"

  # Java -------------------------------------------------------------------------
  - travis_fold start "Setting_up_Java"
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt install -q openjdk-${VERSION_JAVA}-jdk
  - travis_fold end   "Setting_up_Java"
    
  # Gradle -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Gradle"
  - wget -q https://services.gradle.org/distributions/gradle-${VERSION_GRADLE}-bin.zip -P /tmp
  - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-${VERSION_GRADLE}
  - export PATH=${GRADLE_HOME}/bin:${PATH}
  - travis_fold end   "Setting_up_Gradle"

  # Oracle Instant Client for Linux x86-64 (64-bit) ------------------------------
  - travis_fold start "Setting_up_Oracle Instant Client"
  - sudo apt-get install -q libaio1
  - sudo chmod +x $PWD/priv/oracle/instantclient-linux.x64/instantclient_${VERSION_ORACLE_INSTANT_CLIENT}/sqlplus
  - export LD_LIBRARY_PATH=$PWD/priv/oracle/instantclient-linux.x64/instantclient_${VERSION_ORACLE_INSTANT_CLIENT}
  - travis_fold end   "Setting_up_Oracle Instant Client"

  # Python -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Python"
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt install -q python3
  - sudo apt install -q python3-venv
  - python3 -m venv _build/ora_bench-env
  - source _build/ora_bench-env/bin/activate
  - python -m pip install -q --upgrade pip
  - python -m pip install -q --upgrade cx_Oracle
  - travis_fold end   "Setting_up_Python"

  # Setting up environment variables ---------------------------------------------
  - travis_fold start "Setting_up_environment_variables"
  - export ORA_BENCH_MULTIPLE_RUN=true

  - export ORA_BENCH_BENCHMARK_COMMENT='Standard tests (Travis CI)'
  - export ORA_BENCH_CONNECTION_HOST=0.0.0.0
  - export ORA_BENCH_CONNECTION_PORT=1521
  - export ORA_BENCH_CONNECTION_SERVICE=orclpdb1
  - export ORA_BENCH_FILE_CONFIGURATION_NAME=priv/properties/ora_bench.properties
  - export ORA_BENCH_JAVA_CLASSPATH=.:priv/java_jar/*
  - export ORA_BENCH_PASSWORD_SYS=oracle

  - export ORA_BENCH_RUN_DB_12_2_EE=true
  - export ORA_BENCH_RUN_DB_18_3_EE=true
  - export ORA_BENCH_RUN_DB_19_3_EE=true

  - export ORA_BENCH_RUN_CX_ORACLE_PYTHON=true
  - export ORA_BENCH_RUN_GODROR_GO=true
  - export ORA_BENCH_RUN_JAMDB_ORACLE_ERLANG=true
  - export ORA_BENCH_RUN_JDBC_JAVA=true
  - export ORA_BENCH_RUN_ODPI_C=true
  - export ORA_BENCH_RUN_ORANIF_ERLANG=true

  - export ORA_BENCH_BENCHMARK_BATCH_SIZE_DEFAULT=256
  - export ORA_BENCH_BENCHMARK_CORE_MULTIPLIER_DEFAULT=0
  - export ORA_BENCH_BENCHMARK_TRANSACTION_SIZE_DEFAULT=512
  - travis_fold end   "Setting_up_environment_variables"

  # Running ora_bench ------------------------------------------------------------
  - travis_fold start "Running_ora_bench"
  - git pull
  - sudo chmod +x *.sh
  - sudo chmod +x */scripts/*.sh
  - sudo chmod +x scripts/*.sh
  - cd src_java
  - chmod +x gradlew
  - gradle wrapper
  # - cd ../src_kotlin
  # - gradle wrapper
  - cd ..
  - ./scripts/run_properties_variations.sh
  - travis_fold end   "Running_ora_bench"

after_success:
  - ./scripts/run_travis_push_to_github.sh
