---
dist: xenial

sudo: true

language: erlang
otp_release:
  - 23.0

env:
  matrix:
    - ORA_BENCH_CHOICE_DB=12 ORA_BENCH_BENCHMARK_JAMDB=false ORA_BENCH_CHOICE_DRIVER=complete
    - ORA_BENCH_CHOICE_DB=12 ORA_BENCH_BENCHMARK_JAMDB=true  ORA_BENCH_CHOICE_DRIVER=complete
    - ORA_BENCH_CHOICE_DB=18 ORA_BENCH_BENCHMARK_JAMDB=false ORA_BENCH_CHOICE_DRIVER=complete
    - ORA_BENCH_CHOICE_DB=18 ORA_BENCH_BENCHMARK_JAMDB=true  ORA_BENCH_CHOICE_DRIVER=complete
    - ORA_BENCH_CHOICE_DB=19 ORA_BENCH_BENCHMARK_JAMDB=false ORA_BENCH_CHOICE_DRIVER=complete
    - ORA_BENCH_CHOICE_DB=19 ORA_BENCH_BENCHMARK_JAMDB=true  ORA_BENCH_CHOICE_DRIVER=complete
      
    - cx_Oracle Python ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=python
    - GoDROR    Go     ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=go
#   - JamDB     Erlang ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=erlang_jamdb
    - JDBC      Java   ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=java
    - JDBC      Kotlin ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=kotlin
    - ODPI      C      ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=c
    - oranif    Elixir ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=elixir
#   - oranif    Erlang ORA_BENCH_CHOICE_DB=19 ORA_BENCH_CHOICE_DRIVER=erlang_oranif

script:
  # Prepare installation process -------------------------------------------------
  - travis_fold start "Prepare_installation_process"
  - export VERSION_ELIXIR=1.10.4
  - export VERSION_GO=1.15.2
  - export VERSION_GRADLE=6.6.1
  - export VERSION_JAVA=15
  - export VERSION_ORACLE_INSTANT_CLIENT_1=19
  - export VERSION_ORACLE_INSTANT_CLIENT_2=8
    
  - sudo apt update -q
  - sudo apt install -q software-properties-common
  - sudo apt-get install -q lsb-core
  - travis_fold end   "Prepare_installation_process"

  # Elixir -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Elixir"
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  - cd ~/.asdf
  - git checkout "$(git describe --abbrev=0 --tags)"
  - echo -e '\n. ${HOME}/.asdf/asdf.sh' >> ~/.bashrc
  - echo -e '\n. ${HOME}/.asdf/completions/asdf.bash' >> ~/.bashrc
  - cd /home/travis/build/KonnexionsGmbH/ora_bench
  - . ~/.bashrc
  - asdf plugin-add Elixir https://github.com/asdf-vm/asdf-elixir
  - asdf install Elixir ${VERSION_ELIXIR}   
  - asdf global Elixir ${VERSION_ELIXIR}
  - mix local.hex --force
  - mix local.rebar --force
  - travis_fold end   "Setting_up_Elixir"

  # Go ---------------------------------------------------------------------------
  - travis_fold start "Setting_up_Go"
  - wget -q https://dl.google.com/go/go${VERSION_GO}.linux-amd64.tar.gz
  - tar -xf go${VERSION_GO}.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOPATH=${HOME}/build/KonnexionsGmbH/ora_bench/src_go
  - export GOROOT=/usr/local/go
  - export PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH}
  - travis_fold end   "Setting_up_Go"

  # Java -------------------------------------------------------------------------
  - travis_fold start "Setting_up_Java"
  - wget -q https://download.java.net/java/GA/jdk${VERSION_JAVA}/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-${VERSION_JAVA}_linux-x64_bin.tar.gz
  - tar -xf openjdk-${VERSION_JAVA}_linux-x64_bin.tar.gz
  - mv jdk-${VERSION_JAVA} /opt/
  - export JAVA_HOME=/opt/jdk-${VERSION_JAVA}
  - export PATH="${JAVA_HOME}/bin:${PATH}"
  - travis_fold end   "Setting_up_Java"
    
  # Gradle -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Gradle"
  - wget -q https://services.gradle.org/distributions/gradle-${VERSION_GRADLE}-bin.zip -P /tmp
  - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-${VERSION_GRADLE}
  - export PATH=${GRADLE_HOME}/bin:${PATH}
  - travis_fold end   "Setting_up_Gradle"

  # Kotlin -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Kotlin"
  - curl -s https://get.sdkman.io | bash 
  - chmod a+x "$HOME/.sdkman/bin/sdkman-init.sh" 
  - source "$HOME/.sdkman/bin/sdkman-init.sh" 
  - sdk install kotlin
  - travis_fold end   "Setting_up_Kotlin"

  # Oracle Instant Client --------------------------------------------------------
  - travis_fold start "Setting_up_Oracle_Instant_Client"
  - wget -q https://download.oracle.com/otn_software/linux/instantclient/${VERSION_ORACLE_INSTANT_CLIENT_1}${VERSION_ORACLE_INSTANT_CLIENT_2}00/oracle-instantclient${VERSION_ORACLE_INSTANT_CLIENT_1}.${VERSION_ORACLE_INSTANT_CLIENT_2}-basic-${VERSION_ORACLE_INSTANT_CLIENT_1}.${VERSION_ORACLE_INSTANT_CLIENT_2}.0.0.0-1.x86_64.rpm
  - wget -q https://download.oracle.com/otn_software/linux/instantclient/${VERSION_ORACLE_INSTANT_CLIENT_1}${VERSION_ORACLE_INSTANT_CLIENT_2}00/oracle-instantclient${VERSION_ORACLE_INSTANT_CLIENT_1}.${VERSION_ORACLE_INSTANT_CLIENT_2}-sqlplus-${VERSION_ORACLE_INSTANT_CLIENT_1}.${VERSION_ORACLE_INSTANT_CLIENT_2}.0.0.0-1.x86_64.rpm
  - sudo alien -i --scripts *.rpm
  - export ORACLE_HOME=/usr/lib/oracle/${VERSION_ORACLE_INSTANT_CLIENT_1}.${VERSION_ORACLE_INSTANT_CLIENT_2}/client64
  - export LD_LIBRARY_PATH="$ORACLE_HOME/lib:$LD_LIBRARY_PATH"
  - export PATH="$ORACLE_HOME::${PATH}"
  - travis_fold end   "Setting_up_Oracle_Instant_Client"

  # Python -----------------------------------------------------------------------
  - travis_fold start "Setting_up_Python"
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt install -q python3
  - sudo apt install -q python3-venv
  - python3 -m venv _build/ora_bench-env
  - source _build/ora_bench-env/bin/activate
  - travis_fold end   "Setting_up_Python"

  # Setting up environment variables ---------------------------------------------
  - travis_fold start "Setting_up_environment_variables"
  - export ORA_BENCH_MULTIPLE_RUN=true

  - export ORA_BENCH_BENCHMARK_COMMENT='Standard tests (Travis CI)'
  - export ORA_BENCH_CONNECTION_HOST=localhost
  - export ORA_BENCH_CONNECTION_PORT=1521
  - export ORA_BENCH_CONNECTION_SERVICE=orclpdb1
  - export ORA_BENCH_FILE_CONFIGURATION_NAME=priv/properties/ora_bench.properties
  - export ORA_BENCH_PASSWORD_SYS=oracle

  - export ORA_BENCH_BENCHMARK_BATCH_SIZE_DEFAULT=256
  - export ORA_BENCH_BENCHMARK_CORE_MULTIPLIER_DEFAULT=0
  - export ORA_BENCH_BENCHMARK_TRANSACTION_SIZE_DEFAULT=512
  - travis_fold end   "Setting_up_environment_variables"

  # Running ora_bench ------------------------------------------------------------
  - travis_fold start "Running_ora_bench"
  - git pull
  - sudo chmod +x *.sh
  - sudo chmod +x */scripts/*.sh
  - sudo chmod +x scripts/*.sh
  - python -m pip install -r src_python/requirements.txt
  - ./scripts/run_properties_variations.sh
  - travis_fold end   "Running_ora_bench"

after_success:
  - ./scripts/run_travis_push_to_github.sh
