sudo: true
language: erlang
otp_release:
  - 20.3
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java11-installer-local
script:
  - pwd
  - ls -l *.sh
  - chmod +x *.sh
  - ./run_bench.sh
