sudo: true

language: erlang
otp_release:
  - 20.3

env:
  - ORA_BENCH_BENCHMARK_DATABASE=db_11_2_xe

before_install:
  - sudo apt-get update
  - sudo apt-get install default-jdk

after_success:
  - ./run_bench_travis_push.sh

script:
  - java -version
  - chmod +x *.sh
  - chmod +x priv/sqlcl/bin/sql
  - export ORA_BENCH_JAVA_CLASSPATH=.:priv/java_jar/*
  - ./run_bench_database.sh
