dist: xenial
sudo: true
language: erlang
otp_release:
- 20.3

env:
  matrix:
    - ORA_BENCH_BENCHMARK_DATABASE=db_12_2_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_18_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1                                                                        ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1                                  ORA_BENCH_BENCHMARK_CORE_MULTIPLIER=1 ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0                                       ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0 ORA_BENCH_BENCHMARK_CORE_MULTIPLIER=1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0 ORA_BENCH_BENCHMARK_CORE_MULTIPLIER=1 ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0

before_install:
- sudo apt update
# Java -------------------------------------------------------------------------
- sudo apt install default-jdk
- java -version
# Oracle Instant Client for Linux x86-64 (64-bit) ------------------------------
- sudo yum install libaio
- export LD_LIBRARY_PATH=priv/oracle/instantclient-linux.x64/instantclient_19_5:$LD_LIBRARY_PATH
# Python -----------------------------------------------------------------------
- sudo apt install software-properties-common
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt install python3
- python3 --version
- sudo apt install python3-venv
- python3 -m venv my-project-env
- source my-project-env/bin/activate
- python -V
- python -m pip install --upgrade pip
- python -m pip install --upgrade cx_Oracle

script:
- export ORA_BENCH_BENCHMARK_COMMENT='Standard tests (Travis CI)'
- export ORA_BENCH_JAVA_CLASSPATH=.:priv/java_jar/*
- git pull
- ./scripts/run_bench_setup.sh
- ./scripts/run_bench_database.sh
- ./scripts/run_bench_finalise.sh

after_success:
- "./scripts/run_bench_travis_push.sh"
