sudo: true
language: erlang
otp_release:
  - 20.3
before_install:
  - sudo apt-get update
  - sudo apt-get install default-jdk
script:
  - java -version
  - chmod +x *.sh
  - chmod +x priv/sqlcl/bin/sql
  - ./run_bench.sh
