dist: xenial
sudo: true
language: erlang
otp_release:
- 20.3

env:
  matrix:
    - ORA_BENCH_BENCHMARK_DATABASE=db_11_2_xe ORA_BENCH_CONNECTION_SERVICE=xe
    - ORA_BENCH_BENCHMARK_DATABASE=db_12_2_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_18_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMAR_BATCH_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1                                 ORA_BENCH_BENCHMAR_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMAR_BATCH_SIZE=0 ORA_BENCH_BENCHMAR_TRANSACTION_SIZE=0

before_install:
- sudo apt update
# Java -------------------------------------------------------------------------
- sudo apt install default-jdk
- java -version
# Oracle Instant Client for Linux x86-64 (64-bit) ------------------------------
- sudo apt-get install alien
- sudo alien priv/oracle/oracle-instantclient19.3-basiclite-19.3.0.0.0-1.x86_64.rpm
- sudo dpkg -i oracle-instantclient19.3-basiclite_19.3.0.0.0-2_amd64.deb
# Python -----------------------------------------------------------------------
- sudo apt install software-properties-common
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt install python3
- python3 --version
- sudo apt install python3-venv
- python3 -m venv my-project-env
- source my-project-env/bin/activate
- python -V
- python -m pip install --upgrade pip
- python -m pip install --upgrade cx_Oracle

script:
- export ORA_BENCH_BENCHMARK_COMMENT='Standard tests (Travis CI)'
- export ORA_BENCH_JAVA_CLASSPATH=.:priv/java_jar/*
- git pull
- ./scripts/run_bench_setup.sh
- ./scripts/run_bench_database.sh

after_success:
- "./scripts/run_bench_travis_push.sh"
