---
dist: xenial

sudo: true

language: erlang
otp_release:
  - 20.3

env:
  matrix:
    - ORA_BENCH_BENCHMARK_DATABASE=db_12_2_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_18_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1                                                                        ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1                                  ORA_BENCH_BENCHMARK_CORE_MULTIPLIER=1 ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0                                       ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0 ORA_BENCH_BENCHMARK_CORE_MULTIPLIER=1
    - ORA_BENCH_BENCHMARK_DATABASE=db_19_3_ee ORA_BENCH_CONNECTION_SERVICE=orclpdb1 ORA_BENCH_BENCHMARK_BATCH_SIZE=0 ORA_BENCH_BENCHMARK_CORE_MULTIPLIER=1 ORA_BENCH_BENCHMARK_TRANSACTION_SIZE=0

before_install:
  - sudo apt update
  - sudo apt install software-properties-common
  # Elixir -----------------------------------------------------------------------
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  - pwd
  - cd ~/.asdf
  - git checkout "$(git describe --abbrev=0 --tags)"
  - echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
  - echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
  - cd /home/travis/build/KonnexionsGmbH/ora_bench
  - pwd
# - sudo apt install automake autoconf libreadline-dev libncurses-dev libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev unzip curl
  - . ~/.bashrc
  - asdf plugin-add Elixir asdf-vm/asdf-elixir
  - asdf install Elixir 1.9.4   
  - elixir -v
  - mix local.hex --force
  - mix local.rebar --force
  - rebar3 version
  # Java -------------------------------------------------------------------------
  - sudo apt install default-jdk
  - java -version
  # Oracle Instant Client for Linux x86-64 (64-bit) ------------------------------
  - sudo apt-get install libaio1
  - export LD_LIBRARY_PATH=priv/oracle/instantclient-linux.x64/instantclient_19_5:$LD_LIBRARY_PATH
  - sudo chmod +x priv/oracle/instantclient-linux.x64/instantclient_19_5/sqlplus
  # Python -----------------------------------------------------------------------
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt install python3
  - python3 --version
  - sudo apt install python3-venv
  - python3 -m venv _build/ora_bench-env
  - source _build/ora_bench-env/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade cx_Oracle

script:
  - export ORA_BENCH_BENCHMARK_COMMENT='Standard tests (Travis CI)'
  - export ORA_BENCH_JAVA_CLASSPATH=.:priv/java_jar/*
  - git pull
  - ./scripts/run_bench_setup.sh
  - export ORA_BENCH_RUN_JAMDB_ORACLE_ELIXIR=false
  - ./scripts/run_bench_database.sh
  - ./scripts/run_bench_finalise.sh

after_success:
  - "./scripts/run_bench_travis_push.sh"
