[package]
name = "orabench_rs"
version = "1.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
java-properties = "1.4.0"
log = "0.4.14"
#oracle = "0.5.3"
