FROM ubuntu:20.04 as base

ARG DEBIAN_FRONTEND=noninteractive
ARG VERSION_ERLANG_SOLUTIONS=2.0
ARG VERSION_GO=1.14
ARG VERSION_GRADLE=6.2
ARG VERSION_ORACLE_INSTANT_CLIENT=19_5

# Supplement necessary system software -----------------------------------------
RUN apt-get update \
 && apt-get install -qy \ 
 && apt-get install -qy lsb-core

RUN apt-get install -qy software-properties-common

RUN apt-get install -qy wget \
 && wget -q https://packages.erlang-solutions.com/erlang-solutions_${VERSION_ERLANG_SOLUTIONS}_all.deb \
 && dpkg -i erlang-solutions_${VERSION_ERLANG_SOLUTIONS}_all.deb

RUN apt-get install -qy autoconf \
                       autotools-dev \ 
                       build-essential

RUN wget -q https://dl.google.com/go/go${VERSION_GO}.linux-amd64.tar.gz \
 && tar -xf go${VERSION_GO}.linux-amd64.tar.gz \
 && mv go /usr/local

RUN apt-get remove -y docker docker-engine docker.io \
 && apt-get install -qy docker.io

RUN apt-get install -qy default-jdk

RUN wget -q https://services.gradle.org/distributions/gradle-${VERSION_GRADLE}-bin.zip -P /tmp \
 && apt-get install -qy unzip \
 && unzip -d /opt/gradle /tmp/gradle-*.zip

RUN apt-get install -qy git \
 && git config --global credential.helper 'cache --timeout 3600'

RUN apt-get install -qy iputils-ping \
                       language-pack-de

RUN ln -fs /usr/share/zoneinfo/Europe/Zurich /etc/localtime \
 && apt-get install -qy tzdata \
 && dpkg-reconfigure --frontend noninteractive tzdata

RUN wget -q https://s3.amazonaws.com/rebar3/rebar3 \
 && chmod +x rebar3 \
 && mv rebar3 /usr/bin \
 && apt-get install -qy erlang

RUN apt-get install -qy elixir \
 && mix local.hex --force \
 && mix local.rebar --force

RUN apt-get install -qy libaio1

RUN apt-get install -qy python3 \
 && apt-get install -qy python3-venv \
 && wget -q https://bootstrap.pypa.io/get-pip.py \
 && python3 get-pip.py \
 && python3 -m pip install --upgrade cx_Oracle

RUN apt-get install -qy dos2unix \
                        htop \
                        tmux \
                        vim

# Setting Environment Variables ------------------------------------------------
ENV GOPATH=/ora_bench/src_go/go \
    GOROOT=/usr/local/go \
    GRADLE_HOME=/opt/gradle/gradle-${VERSION_GRADLE}

ENV LD_LIBRARY_PATH="/ora_bench/priv/oracle/instantclient-linux.x64/instantclient_${VERSION_ORACLE_INSTANT_CLIENT}:$LD_LIBRARY_PATH" \
    PATH="${GOPATH}/bin:${GOROOT}/bin:${GRADLE_HOME}/bin:/ora_bench/priv/oracle/instantclient-linux.x64/instantclient_${VERSION_ORACLE_INSTANT_CLIENT}:/usr/local/lib/nodejs/bin:${PATH}"

RUN echo "=====================================================================> Curent Date: " \
 && date \
# Show Environment Variables ---------------------------------------------------
 && echo "=====================================================================> Environment variable GOPATH: " \
 && echo $GOPATH \
 && echo "=====================================================================> Environment variable GOROOT: " \
 && echo $GOROOT \
 && echo "=====================================================================> Environment variable GRADLE_HOME: " \
 && echo $GRADLE_HOME \
 && echo "=====================================================================> Environment variable LD_LIBRARY_PATH: " \
 && echo $LD_LIBRARY_PATH \
 && echo "=====================================================================> Environment variable PATH: " \
 && echo $PATH \
# Show component versions ------------------------------------------------------
 && echo "=====================================================================> Version  autoconf: " \
 && autoconf -V \
 && echo "=====================================================================> Version  automake: " \
 && automake --version \
 && echo "=====================================================================> Version  dos2unix: " \
 && dos2unix --version \
 && echo "=====================================================================> Version  elixir: " \
 && elixir -v \
 && mix --version \
 && echo "=====================================================================> Version  gcc: " \
 && gcc --version \
 && echo "=====================================================================> Version  git: " \
 && git --version \
 && echo "=====================================================================> Version  go: " \
 && go version \
 && go env \
 && echo "=====================================================================> Version  gradle: " \
 && gradle --version \
 && echo "=====================================================================> Version  htop: " \
 && htop --version \
 && echo "=====================================================================> Version  java: " \
 && java -version \
 && echo "=====================================================================> Version  openssl: " \
 && openssl version -a \
 && echo "=====================================================================> Version  python3: " \
 && python3 --version \
 && pip --version \
 && echo "=====================================================================> Version  rebar3: " \
 && rebar3 version \
 && echo "=====================================================================> Version  tmux: " \
 && tmux -V \
 && echo "=====================================================================> Version  ubuntu: " \
 && lsb_release -a \
 && echo "=====================================================================> Version  vim: " \
 && vim --version \
 && echo "=====================================================================> Version  wget: " \
 && wget --version

CMD ["/bin/bash"]
