FROM ubuntu:20.04 as base

ARG VERSION_ERLANG_SOLUTIONS=2.0
ARG VERSION_GO=1.14
ARG VERSION_GRADLE=6.2
ARG VERSION_ORACLE_INSTANT_CLIENT=19_5

RUN export DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y  

RUN apt-get install -y software-properties-common

RUN apt-get install -y wget \
 && wget -q https://packages.erlang-solutions.com/erlang-solutions_${VERSION_ERLANG_SOLUTIONS}_all.deb \
 && dpkg -i erlang-solutions_${VERSION_ERLANG_SOLUTIONS}_all.deb

RUN apt-get install -y autoconf \
                       autotools-dev \ 
                       build-essential

RUN wget -q https://dl.google.com/go/go${VERSION_GO}.linux-amd64.tar.gz \
 && tar -xf go${VERSION_GO}.linux-amd64.tar.gz \
 && mv go /usr/local

RUN apt-get remove -y docker docker-engine docker.io \
 && apt-get install -y docker.io

RUN apt-get install -y default-jdk

RUN wget -q https://services.gradle.org/distributions/gradle-${VERSION_GRADLE}-bin.zip -P /tmp \
 && apt-get install -y unzip \
 && unzip -d /opt/gradle /tmp/gradle-*.zip

RUN apt-get install -y git \
 && git config --global credential.helper 'cache --timeout 3600'

RUN apt-get install -y iputils-ping \
                       language-pack-de

RUN ln -fs /usr/share/zoneinfo/Europe/Zurich /etc/localtime \
 && apt-get install -y tzdata \
 && dpkg-reconfigure --frontend noninteractive tzdata

RUN wget -q https://s3.amazonaws.com/rebar3/rebar3 \
 && chmod +x rebar3 \
 && mv rebar3 /usr/bin \
 && apt-get install -y erlang

RUN apt-get install -y elixir \
 && mix local.hex --force \
 && mix local.rebar --force

RUN apt-get install -y libaio1

RUN apt-get install -y python3 \
 && apt-get install -y python3-venv \
 && wget -q https://bootstrap.pypa.io/get-pip.py \
 && python3 get-pip.py \
 && python3 -m pip install --upgrade cx_Oracle

RUN apt-get install -y dos2unix \
                       htop \
                       tmux \
                       vim

ENV GOPATH=/ora_bench/src_go \
    GOROOT=/usr/local/go \
    GRADLE_HOME=/opt/gradle/gradle-${VERSION_GRADLE}

ENV LD_LIBRARY_PATH="/ora_bench/priv/oracle/instantclient-linux.x64/instantclient_${VERSION_ORACLE_INSTANT_CLIENT}:$LD_LIBRARY_PATH" \
    PATH="${GOPATH}/bin:${GOROOT}/bin:${GRADLE_HOME}/bin:/ora_bench/priv/oracle/instantclient-linux.x64/instantclient_${VERSION_ORACLE_INSTANT_CLIENT}:/usr/local/lib/nodejs/bin:${PATH}"

# Show Environment Variables ---------------------------------------------------
RUN echo GOPATH=$GOPATH \
 && echo GOROOT=$GOROOT \
 && echo GRADLE_HOME=$GRADLE_HOME \
 && echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
 && echo PATH=$PATH
 
# Show component versions ------------------------------------------------------
RUN echo $(autoconf -V) \
 && echo $(automake --version) \
 && echo $(dos2unix --version) \
 && echo $(elixir -v) \
 && echo $(gcc --version) \
 && echo $(git --version) \
 && echo $(go version) \
 && echo $(go env) \
 && echo $(gradle --version) \
 && echo $(htop --version) \
 && echo $(java -version) \
 && echo $(mix --version) \
 && echo $(python3 --version) \
 && echo $(rebar3 version) \
 && echo $(tmux -V) \
 && echo $(lsb_release -a) \
 && echo $(vim --version)

CMD ["/bin/bash"]
